on: push
jobs: 
  debug:
      runs-on: ubuntu-latest
      steps:
        - name: Reveal the actual secret values
          run: |
            echo "=== RAW SECRET VALUES ==="
            echo "HOSTNAME_TEST: '${{ secrets.HOSTNAME_TEST }}'"
            echo "USERNAME: '${{ secrets.USERNAME }}'"
            echo "PW: '${{ secrets.PW }}'"
            
            echo "=== SECRET LENGTHS ==="
            echo "HOSTNAME_TEST length: ${#HOSTNAME_TEST}"
            echo "USERNAME length: ${#USERNAME}"
            echo "PW length: ${#PW}"
          env:
            HOSTNAME_TEST: ${{ secrets.HOSTNAME_TEST }}
            USERNAME: ${{ secrets.USERNAME }}
            PW: ${{ secrets.PW }}
  pull-from-repo:
      runs-on: ubuntu-latest
      steps:
        - name: Pull code from github then build a container from it then deploy it
          uses: appleboy/ssh-action@v1.0.3
          with: 
            host:  ${{ secrets.HOSTNAME_TEST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PW }}
            script: |
                if [ $(echo "$PWD") != "/home/student/py-app/cloud_midtermproject" ]; then
                  cd ~/py-app/cloud_midtermproject
                fi
                git pull
                docker build -t py-app:latest .
                if [ $(docker ps -a -f name=app) ]; then
                  docker stop app
                fi
                docker run -d -p 80:80 --name app --rm py-app:latest
              
