on: push
jobs: 
  pull-from-repo:
      environment: secrets
      runs-on: ubuntu-latest
      steps:
        - name: Pull code from github then build a container from it then deploy it
          uses: appleboy/ssh-action@v1.0.3
          with: 
            host:  ${{ secrets.HOSTNAME_TEST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PW }}
            script: |
                if [ $(echo "$PWD") != "/home/student/py-app/cloud_midtermproject" ]; then
                  cd ~/py-app/cloud_midtermproject
                fi
                git pull
                sudo docker build -t py-app:latest .
                if [ "$(sudo docker ps -a -f name=app)" ]; then
                  sudo docker stop app
                fi
                sudo docker run -d -p 80:80 --name app --rm py-app:latest
              
